name: glint
description: glint Project

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # Model View Controller Plugin
  get: ^4.6.5

  # Firebase Plugin
  # firebase_core: ^1.19.1
  # firebase_auth: ^3.4.1   # - Auth
  # firebase_storage: ^10.3.1   # - Storage
  # firebase_messaging: ^11.4.4   # - FCM
  # flutter_local_notifications: ^9.6.1
  # cloud_firestore: ^3.2.1   # - Firebase Document Database

  # Local Database
  get_storage: ^2.0.3   
  hive: ^2.2.3
  shared_preferences: ^2.0.15

  # Image File
  flutter_svg: ^1.1.1+1
  lottie: ^1.3.0

  # Security
  crypto: ^3.0.2

  # Json
  json_serializable: ^6.3.0
  build_runner: ^2.1.11

  # Lints
  flutter_lints: ^2.0.1

  # Ready to Build App
  flutter_native_splash: ^2.2.4
  flutter_launcher_icons: ^0.9.3

  # SNS LOGIN
  google_sign_in: ^5.4.0

  # HTTP
  dio: ^4.0.6

  # WIDGET
  fluttertoast: ^8.0.9
  shimmer: ^2.0.0

  # UTILL
  intl: ^0.17.0
  uuid: ^3.0.6
  flutter_keyboard_visibility: ^5.3.0
  scroll_date_picker: ^3.6.0
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard/Pretendard-Thin.ttf
          weight: 100
        - asset: fonts/Pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: fonts/Pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: fonts/Pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: fonts/Pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: fonts/Pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: fonts/Pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: fonts/Pretendard/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: fonts/Pretendard/Pretendard-Black.ttf
          weight: 900
